/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the full hybrid retrieval pipeline (synchronous)
         * @description End-to-end retrieval over the chosen `pipeline` configuration. Emits the typed results + per-stage timings + per-result stage scores in a single response. Use `POST /v1/search/stream` for incremental streaming.
         */
        post: operations["search_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the full hybrid retrieval pipeline with SSE per-stage events
         * @description Server-Sent Events stream. Each event has `type` ∈ {intent, stage_start, stage_done, results, done, error} and is emitted as soon as the corresponding stage completes, so the client can show Perplexity-style progress chips.
         */
        post: operations["search_stream_v1_search_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping the retrieval engine */
        get: operations["search_health_v1_search_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full profile detail (skills + summary + roles) */
        get: operations["profile_v1_profile__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/job/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full job detail (skills + responsibilities + raw + enhanced text) */
        get: operations["job_v1_job__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntentResult
         * @description Structured-output schema for the intent classifier.
         */
        IntentResult: {
            /** @description Whether the query is searching for candidates (people) or for jobs/roles. If ambiguous, prefer 'candidates' for verbs like 'find', 'who knows', 'looking for', and 'jobs' for verbs like 'roles', 'positions', 'openings'. */
            target_side: components["schemas"]["TargetSide"];
            /**
             * Query Skills
             * @description Atomic skill names mentioned in the query. Title-cased, deduplicated. Examples: 'Python', 'Selenium', 'Risk Management'. Skip generic words like 'engineer', 'developer', 'role'.
             */
            query_skills?: string[];
            /**
             * Min Proficiency
             * @description Minimum proficiency level requested in the query (Dreyfus 5-stage). Use 'Any' if not specified or unclear.
             * @default Any
             * @enum {string}
             */
            min_proficiency: "Beginner" | "Advanced Beginner" | "Competent" | "Proficient" | "Expert" | "Any";
            /**
             * Designation Hint
             * @description If the query names a specific role or designation (e.g. 'Test Manager', 'Senior Java Developer'), capture it verbatim. Else null.
             */
            designation_hint?: string | null;
            /**
             * Free Text Intent
             * @description The residual semantic chunk after stripping skills + designation. Used as the dense-retrieval query. Can be a paraphrased one-liner.
             */
            free_text_intent: string;
        };
        /** JobDetail */
        JobDetail: {
            /** Id */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "demands_csv" | "jd_zip";
            /** Title */
            title?: string | null;
            /** Designation */
            designation?: string | null;
            /** Industry */
            industry?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Experience Lower
             * @default 0
             */
            experience_lower: number;
            /**
             * Experience Upper
             * @default 0
             */
            experience_upper: number;
            /** Skills */
            skills?: components["schemas"]["JobSkill"][];
            /** Raw Text */
            raw_text?: string | null;
            /** Enhanced Text */
            enhanced_text?: string | null;
            /**
             * Canonical Text
             * @default
             */
            canonical_text: string;
        };
        /** JobSkill */
        JobSkill: {
            /** Skill Id */
            skill_id: string;
            /** Skill Name */
            skill_name: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "must_have" | "good_to_have";
            /** Category */
            category: string;
        };
        /**
         * PipelineMode
         * @enum {string}
         */
        PipelineMode: "bm25" | "dense" | "rrf" | "rrf3" | "rrf3_rerank";
        /** ProfileDetail */
        ProfileDetail: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Years Experience
             * @default 0
             */
            years_experience: number;
            /** Skill Summary */
            skill_summary?: string | null;
            /** Potential Roles */
            potential_roles?: string[];
            /** Skills */
            skills?: components["schemas"]["ProfileSkill"][];
            /**
             * Canonical Text
             * @default
             */
            canonical_text: string;
        };
        /** ProfileSkill */
        ProfileSkill: {
            /** Skill Id */
            skill_id: string;
            /** Skill Name */
            skill_name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "core" | "secondary" | "soft";
            /** Proficiency Label */
            proficiency_label: string;
            /** Proficiency */
            proficiency: number;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Query
             * @description Free-text user query.
             */
            query: string;
            /** @description Force the side to search (candidates/jobs). If null, the intent classifier picks one. */
            target_side?: components["schemas"]["TargetSide"] | null;
            /**
             * @description Which retrieval pipeline configuration to run.
             * @default rrf3_rerank
             */
            pipeline: components["schemas"]["PipelineMode"];
            /**
             * Top K
             * @description Number of results to return.
             * @default 10
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            pipeline: components["schemas"]["PipelineMode"];
            intent: components["schemas"]["IntentResult"];
            /** N Candidates Retrieved */
            n_candidates_retrieved: number;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            timings_ms: components["schemas"]["TimingMs"];
        };
        /** SearchResult */
        SearchResult: {
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            entity: components["schemas"]["SearchResultEntity"];
            stage_scores: components["schemas"]["StageScores"];
        };
        /**
         * SearchResultEntity
         * @description Type-discriminated entity payload (Person OR Job).
         */
        SearchResultEntity: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "person" | "job";
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Designation */
            designation?: string | null;
            /** Title */
            title?: string | null;
            /** Industry */
            industry?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Matched Skills */
            matched_skills?: string[];
            /**
             * Snippet
             * @description Truncated canonical_text for preview.
             * @default
             */
            snippet: string;
        };
        /**
         * StageScores
         * @description Per-stage retrieval scores for one document — used in the explanation drawer.
         */
        StageScores: {
            /** Bm25 */
            bm25?: number | null;
            /** Dense */
            dense?: number | null;
            /** Kg */
            kg?: number | null;
            /** Rrf */
            rrf?: number | null;
            /** Rerank */
            rerank?: number | null;
        };
        /**
         * TargetSide
         * @enum {string}
         */
        TargetSide: "candidates" | "jobs";
        /**
         * TimingMs
         * @description End-to-end stage timings in milliseconds.
         */
        TimingMs: {
            /**
             * Intent
             * @default 0
             */
            intent: number;
            /**
             * Encode
             * @default 0
             */
            encode: number;
            /**
             * Bm25
             * @default 0
             */
            bm25: number;
            /**
             * Dense
             * @default 0
             */
            dense: number;
            /**
             * Kg
             * @default 0
             */
            kg: number;
            /**
             * Rrf
             * @default 0
             */
            rrf: number;
            /**
             * Rerank
             * @default 0
             */
            rerank: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stream_v1_search_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_health_v1_search_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    profile_v1_profile__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_v1_job__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
